version: '3.8'

services:
  web-admin:
    build: .
    container_name: green-aqi-admin
    ports:
      - "3005:3005" 
    environment:
      - NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000
      - PORT=3005 
    restart: always